apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default

data:
  # Configuration data can be set as key-value properties
  database: mongodb
  database_uri: mongodb://localhost:27017

  # Or set as complete file contents (even JSON!)
  keys: |
    image.public.key=771
    rsa.public.key=42
  default.conf: |
    server {
      listen   8080;
      server_name _;
      absolute_redirect  off;
    }