apiVersion: v1
kind: Pod
metadata:
  name: datamover
  namespace: default
spec:
  containers:
  - name: datamover
    image: alpine
    command: ["/bin/ash"]
    args: ["-c", "sleep 10000"]
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 100m
