---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-data-claim
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
  #storageClassName: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deploy
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.4.1-alpine
        ports:
        - containerPort: 2368
        volumeMounts:
        - mountPath: "/var/lib/ghost/content"
          name: ghost-data
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-data-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
#type: NodePort
 type: LoadBalancer
 ports:
 - protocol: TCP
   port: 80
   targetPort: 2368
 selector:
   app: ghost
