---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deploy
  labels:
    app: ghost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3.3-alpine
        ports:
        - containerPort: 2368

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
type: NodePort
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 2368
    
  
    
  
