---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
  namespace: vm-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: vc01cl01-t0compute
  volumeMode: Filesystem
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: harbor-02
  labels:
    app: harbor-02
  namespace: vm-1
spec:
  imageName: centos-stream-8-vmservice-v1alpha1-1638306496810
  className: best-effort-large
  powerState: poweredOn
  storageClass: vc01cl01-t0compute
  networkInterfaces:
  - networkType: vsphere-distributed
    networkName: my-vDS-network
  volumes:
  - name: my-harbor-vol
    persistentVolumeClaim:
      claimName: harbor-pvc
  vmMetadata:
    configMapName: harbor-cm
    #transport: vAppConfig
    transport: OvfEnv

---
apiVersion: v1
kind: ConfigMap
metadata:
# The name of the ConfigMap and the vSphere namespace to create it in
    name: harbor-pv-cm
    namespace: vm-1
# The data (OVF Keys and their values) to pass into the VM at provision time
data:
# This passes in a base64 encoded version of the cloud-init user-data file you will have
# built for the VM - the example below can be easily decoded to readable text by running
# echo 'Big Long String Here' | base64 -d
# on your CLI
  user-data: |
    I2Nsb3VkLWNBhc3N3b3JkIG9mIFZNd2FyZTEhIGFuZCBzZXQgaXQgdG8gbm90IGV4cGlyZQpjaHBhc3NUgYSBkb2NrZXIgdXNlciBncm91cCBvbiB0aGUgT1MKZ3JvdXBzOgogIC0gZG9ja2VyCnVzZXJzOgojIyBDcmVhdGUgdGhlIGRlZmF1bHQgdXNlciBmb3IgdGhlIE9TCiAgLSBkZWZhdWx0CiMjIEN1c3RvbWlzZSB0aGUgY2VudG9zIHVzZXIgY3JlYXRlZCBhYm92ZSBieSBhZGRpbmcgYW4gU1NIIGtleSB0aGF0J3MgYWxsb3dlZCB0byBsb2dpbiB0byB0aGUgVk0KIyMgSW4gdGhpcyBjYXNlLCBpdCdzIHRoZSBTU0ggcHVibGljIGtleSBvZiBteSBsYXB0b3AKICAtIG5hbWU6IGZyamIKICAgIHNzaC1hdXRob3JpemVkLWtleXM6CiAgICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FEb3RyWUwwZFdpc2d3dFAxbXB6Tlc2MGhHR2xrS3dyQWViU0ZMdzg5Q21NaGpNRmVmR0Z0MlNwd3pNc2J6am1qWkJXaUR1aTYyZUhmQWdxa0NJV2xJc2xQUnN1WlVxSUZnaFZFNVNXL3JrVDB3NDFLTk9OSDhsTjZlMS9NcjFDRUJVcU9veisweXNHbVhFSnRidGcwT2pkTVd1UndUQjExRzFMd3Z5eW55NUlnaUFmK2lvd0JoSjd2VTBGNzh1MjRjOW9TN0NzMVNIZS9HZjRJTDAwS3FoZXArSnVKUHNMY1pSZWxyaUtGcEhNanRRSkJQeWR0VFoxMm9PUzNLdWdTZkhFRUlJRmlPTnZlRytVZFZRV2tOMkhrQklXb3loMG9ZTjRudkV2VC9xbXVtQWRSK09KVTRsdzEzMDQxdnlQdjBRaVRZTjFtZ2R5YkVERHBXSWkzWDRtaExkMzhrR2tkYTNVZ01GRytlZmNyZDJXRnoxTTdFdXlKbmpYdzhUZWNZMlVhTFcwQWIxZXZ2azE0bjh0ZUg2L2h5U09FR0YvUEovRk9wR01SeGhFNVE5NWd6KzBSQzhpT2VXSGZQNlZWN2Fzc2tZOWh3M0JVTkZPVTMzVzVZTTFyKzNxK2hiY2I3ZDJJMFdtaDlaazVCRllhUU9qVXA4VlF1TzlXVGVReEU9IGJmYWJpYW5AYmZhYmlhbi1hMDEudm13YXJlLmNvbQojIyBBZGQgdGhlIGNlbnRvcyB1c2VyIHRvIHRoZSBzdWRvIGdyb3VwIGFuZCBhbGxvdyBpdCB0byBlc2NhbGF0ZSB0byBzdWRvIHdpdGhvdXQgYSBwYXNzd29yZAogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgZ3JvdXBzOiBzdWRvLCBkb2NrZXIKIyMgU2V0IHRoZSBkZWZhdWx0IHNoZWxsIG9mIHRoZSB1c2VyIHRvIGJhc2gKICAgIHNoZWxsOiAvYmluL2Jhc2gKIyMgRW5hYmxlIERIQ1Agb24gdGhlIGRlZmF1bHQgbmV0d29yayBpbnRlcmZhY2UgcHJvdmlzaW9uZWQgaW4gdGhlIFZNCm5ldHdvcms6CiAgdmVyc2lvbjogMgogIGV0aGVybmV0czoKICAgICAgZW5zMTkyOgogICAgICAgICAgZGhjcDQ6IHRydWUKcGFja2FnZV91cGRhdGU6IHRydWUKCnBhY2thZ2VzOgogIC0gbmV0LXRvb2xzCiAgLSBjdXJsIAogIC0gd2dldCAKICAtIHZpbQogIC0geXVtLXV0aWxzCgoKcnVuY21kOgogIC0geXVtLWNvbmZpZy1tYW5hZ2VyIC0tYWRkLXJlcG8gaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L2NlbnRvcy9kb2NrZXItY2UucmVwbwogIC0gc3VkbyB5dW0gaW5zdGFsbCAteSBkb2NrZXItY2UgZG9ja2VyLWNlLWNsaSBjb250YWluZXJkLmlvIGRvY2tlci1idWlsZHgtcGx1Z2luIGRvY2tlci1jb21wb3NlLXBsdWdpbiAKICAtIHN5c3RlbWN0bCBlbmFibGUgZG9ja2VyICYmIHN5c3RlbWN0bCBzdGFydCBkb2NrZXI=
# The hostname to assigned to the VM when it is provisioned
  hostname: harbor-02
