---
- hosts: k8s
  remote_user: root
  tasks:
  - name: Stop and disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: false
  - name: disable ufw
    ufw:
      state: disabled
  - name: Disable swap
    shell: swapoff -a
  - sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
      sysctl_set: yes
      reload: yes
