apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: vector # Ensure this matches the namespace where Vector is installed
type: Opaque
data:
  # The password must be Base64 encoded
  password: <YOUR_BASE64_ENCODED_STRING_HERE>
