controller:
  allowSnippetAnnotations: true
  hostNetwork: true
  hostPort:
      # -- Enable 'hostPort' or not
      enabled: true
      ports:
        # -- 'hostPort' http port
        http: 80
        # -- 'hostPort' https port
        https: 443
  service:
    type: ClusterIP
  extraArgs:
    enable-ssl-passthrough: true
  kind: DaemonSet
