apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  nginx-deployment
spec:
  selector:
    matchLabels:
      app:  nginx
  replicas:  4
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image:  nginx:1.8
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
