version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - webfront
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 250M
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8090:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webfront


networks:
  webfront:
