apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ScanPolicy
metadata:
  name: scan-policy
  labels:
    'app.kubernetes.io/part-of': 'component-a'
  namespace: backend

spec:
  regoFile: |
    package main

    # Accepted Values: "Critical", "High", "Medium", "Low", "Negligible", "UnknownSeverity"
    notAllowedSeverities := ["Critical"]
    ignoreCves := ["CVE-2016-0949", "CVE-2017-11291", "CVE-2018-12804", "CVE-2018-12805", "CVE-2018-4923", "CVE-2021-40719", "CVE-2018-25076", "GHSA-rprw-h62v-c2w7", "GHSA-8q59-q68h-6hv4", "GHSA-6757-jp84-gxfx", "CVE-2017-18342", "CVE-2022-35255", "CVE-2018-25076", "CVE-2021-40719", "CVE-2018-4923", "CVE-2018-12805", "CVE-2018-12804", "CVE-2017-11291", "CVE-2016-0949", "CVE-2022-37434", "CVE-2018-16395", "CVE-2015-0244", "CVE-2015-3166", "CVE-2018-1115", "CVE-2019-10211", "GHSA-36p3-wjmg-h94x", "CVE-2016-1000027"]

    contains(array, elem) = true {
      array[_] = elem
    } else = false { true }

    isSafe(match) {
      severities := { e | e := match.ratings.rating.severity } | { e | e := match.ratings.rating[_].severity }
      some i
      fails := contains(notAllowedSeverities, severities[i])
      not fails
    }

    isSafe(match) {
      ignore := contains(ignoreCves, match.id)
      ignore
    }

    deny[msg] {
      comps := { e | e := input.bom.components.component } | { e | e := input.bom.components.component[_] }
      some i
      comp := comps[i]
      vulns := { e | e := comp.vulnerabilities.vulnerability } | { e | e := comp.vulnerabilities.vulnerability[_] }
      some j
      vuln := vulns[j]
      ratings := { e | e := vuln.ratings.rating.severity } | { e | e := vuln.ratings.rating[_].severity }
      not isSafe(vuln)
      msg = sprintf("CVE %s %s %s", [comp.name, vuln.id, ratings])
    }
