apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod
  name: secretpod
spec:
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      optional: true
  containers:
  - image: nginx
    name: secretpod
    resources: {}
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
