apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tools
  name: tools
spec:
  containers:
  - image: harbor.fbclouddemo.us/publicimages/ubuntu-tools-focal@sha256:91db68c3f2ef07151fd4f3674c857420107822d0f15f353e6bf3e061537dbaff
    name: tools
    command:
    - sleep
    - "90000"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
