apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-bronze
  labels:
    release: test-bronze
spec:
  storageClassName: bronze
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Mi