apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  labels:
    release: test
spec:
  storageClassName: thin
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Mi
