apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-silver
  labels:
    release: test-silver
spec:
  storageClassName: silver
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Mi