apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-gold
  labels:
    release: test-gold
spec:
  storageClassName: gold
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Mi