apiVersion:  v1
kind:  Service
metadata:
  name:  web-deployment
  labels:
    app:  fb-web
spec:
  #type:  LoadBalancer
  type:  NodePort
  ports:
  - port:  80
    protocol:  TCP
  selector:
    app:  fb-web

---
apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  web-deployment
spec:
  selector:
    matchLabels:
      app:  fb-web
  replicas:  4
  template:
    metadata:
      labels:
        app:  fb-web
    spec:
      containers:
      - name:  fb-web
        image:  fabianbrash/nginx:1.0
        ports:
        - containerPort: 80
