apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: win-framework
  name: win-framework
  namespace: framework-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: win-framework
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: win-framework
    spec:
      containers:
      - image: harbor.fbclouddemo.us/windows/mcr.microsoft.com/dotnet/framework/samples@sha256:7fe9ebf1dfe8cb71232b9e196720c5fd34777cfff0e0ecb3be32eb00dee89ef8
        name: win-framework
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: "os"
          operator: "Equal"
          value: "windows"
          effect: "NoSchedule"
status: {}
