
version: '3.1'

services:

  mysql:
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    volumes:
      - "/mysql:/var/lib/mysql"
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 2048M
      placement:
        constraints: [node.role == manager]
    networks:
      - wpnetwork
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/my_secret
    secrets:
      - my_secret

  wp:
    image: wordpress
    ports:
      - "80:80"
    volumes:
      - "/wp:/var/www/html"
    networks:
      - wpnetwork
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
      mode: replicated
      replicas: 5
    environment:
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/my_secret
    secrets:
      - my_secret

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - wpnetwork

secrets:
  my_secret:
    external: true

networks:
  wpnetwork:
